server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/ossaw/config-repo
          search-paths: licensingservice, organizationservice
          username: ossaw
          password: asd741852963.+
encrypt:
  key: JIANGHAO